### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by fatso83** [fatso83/mini-mocha#15]
```
npm ERR! AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
npm ERR! + actual - expected
npm ERR! 
npm ERR! + '{ [Symbol(RunKit Simple Value Viewer)]:\n   { title: \'main describe 1\',\n     HTML:\n      `<table><thead>main describe 1</thead><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">main describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ main describe 1 block standalone it</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 1</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 1 (Failed with: "Expected values to be strictly equal:<br/><br/>\'1\' !== \'2\'<br/>")</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 2 from inner describe 2</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2 deep describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2 deep describe 1</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 2 deep describe 1 (Failed with: "Expected values to be strictly equal:<br/><br/>\'1\' !== \'2\'<br/>")</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2 deep describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2 deep describe 2</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 2 deep describe 2 (Failed with: "Expected values to be strictly equal:<br/><br/>\'1\' !== \'2\'<br/>")</p></td></tr></table>` } }\n{ [Symbol(RunKit Simple Value Viewer)]:\n   { title: \'main describe 2\',\n     HTML:\n      \'<table><thead>main describe 2</thead><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">main describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ main describe 2 block standalone it</p></td></tr></table>\' } }\n'
npm ERR! - `{ [Symbol(RunKit Simple Value Viewer)]:\n   { title: 'main describe 1',\n     HTML:\n      '<table><thead>main describe 1</thead><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">main describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ main describe 1 block standalone it</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 1</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 1 (Failed with: "Input A expected to strictly equal input B:<br/>+ expected - actual<br/><br/>- \\'1\\'<br/>+ \\'2\\'")</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 2 from inner describe 2</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2 deep describe 1</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2 deep describe 1</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 2 deep describe 1 (Failed with: "Input A expected to strictly equal input B:<br/>+ expected - actual<br/><br/>- \\'1\\'<br/>+ \\'2\\'")</p></td></tr><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">inner describe 2 deep describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ it 1 from inner describe 2 deep describe 2</p></td></tr><tr><td><p style="color: #c00;font-size: 12px;display: block;float: left;">✖ it 2 from inner describe 2 deep describe 2 (Failed with: "Input A expected to strictly equal input B:<br/>+ expected - actual<br/><br/>- \\'1\\'<br/>+ \\'2\\'")</p></td></tr></table>' } }\n{ [Symbol(RunKit Simple Value Viewer)]:\n   { title: 'main describe 2',\n     HTML:\n      '<table><thead>main describe 2</thead><tr><td><p style="color: #005cd6;font-size: 12px;display: block;float: left;">main describe 2</p></td></tr><tr><td><p style="color: #00d6b2;font-size: 12px;display: block;float: left;">✓ main describe 2 block standalone it</p></td></tr></table>' } }\n`
npm ERR!     at runTest (/home/carlerik/dev/mini-mocha/test/tests.js:50:10)
npm ERR!     at exec (/home/carlerik/dev/mini-mocha/test/helper.js:19:14)
npm ERR!     at ChildProcess.exithandler (child_process.js:288:7)
npm ERR!     at ChildProcess.emit (events.js:193:13)
npm ERR!     at maybeClose (internal/child_process.js:1001:16)
```

**Comment by rpgeeganage** [comment]
It seems I can't recreate the same failure in my environment. :(

**Comment by rpgeeganage** [comment]
I recreated the error in Docker image for `node:8.15.1`

**Comment by fatso83** [comment]
I guess that's touching on the problem with integration tests: they often utilize bits outside of your own control. I now set up Circle CI to run on[ both Node 10 and Node 12](https://github.com/fatso83/mini-mocha/blob/master/.circleci/config.yml#L55-L56), so we should now get notified.
